version: '3.9'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: webapp:2.0
    ports:
      - "80:5000" # double quotes used here
    restart: always
    networks: 
      - webnet
networks:
  webnet:
